// ***************************************************************************** //
// build.gradle
// for versioning see gradle.properties
//
// ***************************************************************************** //
buildscript {

    repositories {
        mavenCentral()
        maven { url = "https://maven.minecraftforge.net" }
    }

    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT"
    }

}
apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'maven'

version = "${mc_version}-${mod_version}.${mod_build}"
group = "${mod_group}"
archivesBaseName = "${mod_name}"

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "${mc_version}-${forge_version}"
    runDir = "run"
    mappings = "${mcp_mappings}"
    
    replace '@MOD_VERSION@', "${mod_version}.${mod_build}"
    replace '@MOD_SIGNATURE@', "${mod_signature}"
    replaceIn 'Cyberware.java'
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    // All compile-time dependencies from libs folder
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
}

processResources {
    inputs.property "version", version
    inputs.property "mcversion", project.mc_version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': "${mod_version}.${mod_build}", 'mcversion': project.mc_version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    exclude "**/TODO.txt"
    exclude "**/update-dist.json"
    destinationDir = file('output')
    
    manifest {
        attributes FMLAT: "cyberware_at.cfg"
    }
}

task devJar(type: Jar) {
    from sourceSets.main.output
    classifier = 'dev'
    destinationDir = file('output')
}

task apiJar(type: Jar) {
    from(sourceSets.main.allJava) {
        include 'flaxbeard/cyberware/api/**'
    }
    from(sourceSets.main.output) {
        include 'flaxbeard/cyberware/api/**'
    }
    classifier = 'api'
    destinationDir = file('output')
}

artifacts {
    archives devJar
    archives apiJar
}

task signJar(type: SignJar, dependsOn: reobfJar) {
    onlyIf {
        project.hasProperty('keyStore')
    }
    
    keyStore = project.findProperty('keyStore')
    alias = project.findProperty('keyStoreAlias')
    storePass = project.findProperty('keyStorePass')
    keyPass = project.findProperty('keyStoreKeyPass')
    inputFile = jar.archivePath
    outputFile = jar.archivePath
}

build.dependsOn signJar
