# ~/.gradle/gradle.properties
#
#org.gradle.daemon=true
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-8.0.472.8-hotspot

# If you're behind a proxy, uncomment and configure:
#systemProp.http.proxyHost=your-proxy-host
#systemProp.http.proxyPort=8080
#systemProp.https.proxyHost=your-proxy-host
#systemProp.https.proxyPort=8080

mod_signature=67a0e286dc0d4b502f3c92ac20b953517b52d0a9
mod_group=flaxbeard.cyberware
mod_name=Cyberware-Community-Edition
mod_version=0.2.11
mod_build=29

mcp_mappings=stable_39
forge_version=14.23.5.2838
mc_version=1.12.2

# Working versions that can be downloaded
jei_version=4.16.1.302
botania_version=r1.10-364
tesla_version=1.0.63

curse_project=283377
